name = "Markdoc"
grammar = "markdoc"
path_suffixes = ["mdoc", "markdoc"]
line_comments = ["<!-- ", " -->"]
tab_size = 2
hard_tabs = false

[brackets]
"(" = ")"
"{" = "}"
"[" = "]"
"\"" = "\""
"'" = "'"
"`" = "`"

# Markdoc-specific brackets
"{%" = "%}"
"{{" = "}}"