name = "Markdoc"
id = "markdoc"
version = "0.1.0"
schema_version = 1
description = "Markdoc language support: syntax highlighting, file associations, and editor integration using tree-sitter-markdoc."
repository = "https://github.com/louiss0/zed-markdoc-extension"
license = "MIT"
authors = ["Shelton Louis"]

[grammars.markdoc]
repository = "https://github.com/louiss0/tree-sitter-markdoc"
rev = "ca296e9db560ccc027a207baaee57286909c4526"
