name: Release Zed Extension

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish extension update PR
    runs-on: ubuntu-latest
    steps:
      - name: Bump extension in zed-industries/extensions
        uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: markdoc
          push-to: louiss0/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
