name: Release Markdoc Extension

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish extension update PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Bump extension in zed-industries/extensions
        uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: markdoc
          extension-path: extension
          push-to: ${{ github.repository_owner }}/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
